## **Question - 1:**

# Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
# importing numpy 
import numpy as np

# creating a array using numpy arange
arr = np.arange(2, 50, 3)

# printing array
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


## ** Question - 2**

# Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [3]:
# importing numpy 
import numpy as np

# creating a 2 empty list:
list_1 = []
list_2 = []

# for list_1 
for i in range(5):
  x=int(input("\nEnter the value for list 1 : "))
  list_1.append(x)

# for list_2 
for i in range(5):
  x=int(input("\nEnter the value for list 2 : "))
  list_2.append(x)

# list ->  array:
array_1 = np.array(list_1)
array_2 = np.array(list_2)

# concatenate two arrays
array = np.concatenate((array_1, array_2))
print("\nArray value for concatenated arr :",array)

# sorting up concatenated array
sorted_array = np.sort(array)
print("\nSorted Array for concatenated arr :",sorted_array)





Enter the value for list 1 : 1

Enter the value for list 1 : 2

Enter the value for list 1 : 3

Enter the value for list 1 : 4

Enter the value for list 1 : 5

Enter the value for list 2 : 1

Enter the value for list 2 : 2

Enter the value for list 2 : 3

Enter the value for list 2 : 4

Enter the value for list 2 : 5

Array value for concatenated arr : [1 2 3 4 5 1 2 3 4 5]

Sorted Array for concatenated arr : [1 1 2 2 3 3 4 4 5 5]


# ** Question - 3:**

#### Write a code snippet to find the dimensions of a ndarray and its size.

In [4]:
# import numpy
import numpy as np

# created  2-d array
array = np.array([[1,2,3],[1,3,5]])

# Printing array dimensions 
print("\nDimensions of array : ", array.ndim)
 
# Printing size of array
print("\nSize of array : ", array.size)





Dimensions of array :  2

Size of array :  6


## **Question - 4:**

#### How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
##### Hint: np.newaxis, np.expand_dims

In [5]:
# import numpy
import numpy as np

# created 1-d array
array = np.arange(10)
print("\nShape of Array :",array.shape)

# converting using newaxis in row wise
row_array = array[np.newaxis, :]
print("\nShape of 2d Array (ROW MAJOR) :",row_array.shape)

# converting using newaxis in column wise
column_array = array[:, np.newaxis]
print("\nShape of 2d Array in (COLUMN MAJOR) :",column_array.shape)



Shape of Array : (10,)

Shape of 2d Array (ROW MAJOR) : (1, 10)

Shape of 2d Array in (COLUMN MAJOR) : (10, 1)


## **Question - 5:**

#### Consider two square numpy arrays. Stack them vertically and horizontally.

##### Hint: Use vstack(), hstack()

In [6]:
# import numpy
import numpy as np

# creating a array with square values
array_1 = np.square([1, 2, 3, 4, 5])
array_2 = np.square([6, 7, 8, 9, 10])

# stacking and printing the value
print("\nHorizontal Appended Array :", np.hstack((array_1, array_2)))
print("\nVertical Appended Array :", np.vstack((array_1, array_2)))




Horizontal Appended Array : [  1   4   9  16  25  36  49  64  81 100]

Vertical Appended Array : [[  1   4   9  16  25]
 [ 36  49  64  81 100]]


## **Question - 6:**

##### How to get unique items and counts of unique items?



In [7]:
# import numpy
import numpy as np

# create a array 
array= np.array([1, 4, 9, 16, 25, 12, 40, 20, 3, 20, 50, 61, 50, 70, 70, 100])

# unique charater and its count
unique, counts = np.unique(array, return_counts=True)

# making a 
new_array = np.asarray((unique, counts)).T

print(new_array)


[[  1   1]
 [  3   1]
 [  4   1]
 [  9   1]
 [ 12   1]
 [ 16   1]
 [ 20   2]
 [ 25   1]
 [ 40   1]
 [ 50   2]
 [ 61   1]
 [ 70   2]
 [100   1]]
